### ISSUE TITLE
nodehun with VSCode and Webpack

### ISSUE THREAD

**Issue by ChrisChinchilla** [Wulf/nodehun#107]
This is a similar issue to https://github.com/Wulf/nodehun/issues/84 but in may case as I am trying to add spelling suggestions to our Vale VSCode extension and need something to provide the spelling support.

So once I build and run the extension using nodehun, I get

```
notificationsAlerts.ts:40 Error: Cannot find module 'nodehun'
	at webpackMissingModule (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:459:88)
	at ./src/features/vsSpelling.ts (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:459:170)
	at __webpack_require__ (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:916:42)
	at ./src/features/vsProvider.ts (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:243:22)
	at __webpack_require__ (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:916:42)
	at ./src/extension.ts (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:187:38)
	at __webpack_require__ (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:916:42)
	at vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:927:37
	at Object.<anonymous> (vscode-file://vscode-app/xxx/vale-vscode/dist/extension.js:930:12)
	at Module._compile (node:internal/modules/cjs/loader:1165:14)
	at Object..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at node:internal/modules/cjs/loader:876:12
	at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13343)
	at Function.<anonymous> (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
	at Function.<anonymous> (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
	at Function._load (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at d.pb (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:63164)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
```

I would like to try and offer native-level performance in the VSCode extension, but maybe the solution is the same as the older issue sadly? Or is there some other way to get nodehun recognised by web pack?

**Comment by Wulf** [comment]
hey @ChrisChinchilla, hope things are well and happy new year :)

Check this out and see if it helps: https://www.npmjs.com/package/hunspell-asm

It seems to be missing a few methods but maybe you can add them in yourself!

**Comment by ChrisChinchilla** [comment]
Thanks @Wulf ! Though looking at this, this line stands out to me…

> Hunspell exposes few interfaces allow to add words, or dictionaries in existing dictionary in runtime. This is runtime behavior, so it doesn't persist over once instance is disposed.

This might be an issue as people using our extension would kind of expect what they add to suggestions to persist.

Is there a way I could maybe create a fork of your repo to get it to work with web pack, or of you think that's more work than it's worth?

**Comment by Wulf** [comment]
Yeah that’s standard hunspell behaviour —
nodehun is the same. It’s the library user’s responsibility to load extra dictionaries or words when initializing.

**Comment by ChrisChinchilla** [comment]
Ah, I misread that to mean it was wasm that made that a factor, saving words to dictionary files is totally expected.

For the second part of my last question. What would it take to make your code webpack compatible? Or is it an impossibility? I can also see if vscode extensions need webpack top of course, that's just our current process.

**Comment by Wulf** [comment]
hey Chris, sorry I dropped the ball here -- what do you mean by webpack compatible?

**Comment by ChrisChinchilla** [comment]
@Wulf I honestly don't know, the whole ecosystem confuses me, but I have got hunspell-asm working anyway, so thanks!
