### ISSUE TITLE
build error: rror: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by loretoparisi** [Wulf/nodehun#60]
Hello, since this module has been deprecated I'm trying to build from sources, but I'm not sure how. I have `node-gyp` installed, and I do:

```
[loretoparisi@:mbploreto nodehun]$ npm install

> nodehun@2.0.11 install /Users/loretoparisi/Documents/Projects/AI/nodehun
> node-gyp rebuild

make: *** No rule to make target `Release/obj.target/hunspell/src/hunspell/src/hunspell/affentry.o', needed by `Release/hunspell.a'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/loretoparisi/Documents/Projects/AI/nodehun
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! nodehun@2.0.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodehun@2.0.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodehun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodehun
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodehun
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/loretoparisi/Documents/Projects/AI/nodehun/npm-debug.log
```

**Comment by Wulf** [comment]
Hey @loretoparisi I wrote a small section at the bottom of the README:
https://github.com/Wulf/nodehun/blob/nan/readme.md#developmentcontributing

Let me know if `npm build` works for you or not.
Regards

**Comment by loretoparisi** [comment]
@Wulf thanks. On latest commit if I do `npm run build` I get a

```
[loretoparisi@:mbploreto nodehun]$ npm run build
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/loretoparisi/Documents/Projects/AI/nodehun/npm-debug.log
```

error.

**Comment by Wulf** [comment]
I ended up getting the same error, but I made the mistake of not switching to the `nan` branch. Please try re-cloning like below:
```
git clone --recursive -b nan http://github.com/wulf/nodehun nodehun2
cd nodehun2
npm install
npm run dev
```

Also, it's not completely implemented in nan yet; there are many method stubs.
Regards

**Comment by Wulf** [comment]
@loretoparisi did it work out?

**Comment by loretoparisi** [comment]
@Wulf Hello, so I have tried and I get

```
[loretoparisi@:mbploreto nodehun2]$ npm run dev

> Nodehun@2.0.11 dev /Users/loretoparisi/Documents/Projects/AI/nodehun2
> node test/nan.js

Nodehun NAN Implementation Tests
--------------------------------
instance.correctSync("drinkabl")	 false
instance.suggestSync("drinkabl")	 [ 'drinkable', 'sinkable' ]
instance.suggestSync("😀")		 []
instance.correctSync("😀")		 false
instance.suggest("drinkable")		 [ null, true, [] ]
instance.correct("drinkabl")		 [ null, false ]
instance.suggest("drinkabl")		 [ null, false, [ 'drinkable', 'sinkable' ] ]
```

and I can see in `Release`:

```
loretoparisi@:mbploreto build]$ cd Release/
[loretoparisi@:mbploreto Release]$ ls -l
total 6792
-rwxr-xr-x  1 loretoparisi  staff   473592 23 Nov 09:35 Nodehun.node
-rw-r--r--  1 loretoparisi  staff  3001440 23 Nov 09:35 hunspell.a
drwxr-xr-x  4 loretoparisi  staff      136 23 Nov 09:35 obj.target
```

Is it ok? I see the static library here.

**Comment by Wulf** [comment]
Yup! It looks like it compiled :)

Closing this, but feel free to continue the discussion.

**Comment by loretoparisi** [comment]
@Wulf thanks, so due to this module deprecation, what do you suggest to keep support? I have npm as well, so should do I make a fork an publish to npm the forked one? I'm trying to figure out how to maintain this package in the next for projects that have `nodehun` as dependency (directly or not).

Thanks!

**Comment by Wulf** [comment]
@loretoparisi is something wrong with the module? It isn't deprecated, everything should work, even with the latest version of node!

**Comment by Wulf** [comment]
@loretoparisi That was removed in #41 lol, I'm not sure why you see that message.

**Comment by Wulf** [comment]
Also, please see #37 if you'd like to help migrate this project to use [`nan`](https://github.com/nodejs/nan) and have it match the hunspell 3 interface (and other small things like having the constructor follow node conventions). I can help you along :)
