### ISSUE TITLE
error: no matching member function for call to 'NewInstance'

### ISSUE THREAD

**Issue by loretoparisi** [Wulf/nodehun#63]
I have

```
ip-192-168-22-127:webservice loretoparisi$ node -v
v10.1.0
ip-192-168-22-127:webservice loretoparisi$ npm -v
5.6.0
```

stacktrace: 

```
../src/nodehun.cpp:5:2: warning: "Nodehun is no longer being actively maintained. Please email nathanjsweet@gmail.com If you are interested in taking over the
      project." [-W#warnings]
#warning "Nodehun is no longer being actively maintained. Please email nathanjsweet@gmail.com If you are interested in taking over the project."
 ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:92:19: error: no matching member function for call to 'NewInstance'
  argv[1] = cons->NewInstance(1, &ext);
            ~~~~~~^~~~~~~~~~~
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:165:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      String::Utf8Value arg0(args[0]->ToString());
                        ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:186:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      String::Utf8Value arg0(args[0]->ToString());
                        ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:245:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      String::Utf8Value arg0(args[0]->ToString());
                        ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:266:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value arg0(args[0]->ToString());
                      ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:301:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      String::Utf8Value arg0(args[0]->ToString());
                        ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:322:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value arg0(args[0]->ToString());
                      ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:504:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value arg0(args[0]->ToString());
                      ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:545:23: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    String::Utf8Value arg0(args[0]->ToString());
                      ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:607:29: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      v8::String::Utf8Value arg0(args[0]->ToString());
                            ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:626:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value arg0(args[0]->ToString());
                          ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:701:29: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      v8::String::Utf8Value arg0(args[0]->ToString());
                            ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:702:29: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      v8::String::Utf8Value arg1(args[1]->ToString());
                            ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:722:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value arg0(args[0]->ToString());
                          ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:723:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value arg1(args[1]->ToString());
                          ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:790:29: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
      v8::String::Utf8Value arg0(args[0]->ToString());
                            ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/nodehun.cpp:12:
../src/post0.12.0/nodehun.cpp:809:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
    v8::String::Utf8Value arg0(args[0]->ToString());
                          ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/loretoparisi/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
17 warnings and 1 error generated.
make: *** [Release/obj.target/nodehun/src/nodehun.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/loretoparisi/Documents/Projects/musixmatch-ai-console/webservice/node_modules/nodehun
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN musixmatch-ai-console@3.2.4-20180508 No repository field.
npm WARN musixmatch-ai-console@3.2.4-20180508 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodehun@2.0.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodehun@2.0.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/loretoparisi/.npm/_logs/2018-05-11T07_19_57_492Z-debug.log
```

**Comment by Wulf** [comment]
The `nan` branch compiles but it isn't fully implemented yet. (Please see #37 -- would love some help)

Will try to resolve this issue soon!

**Comment by Wulf** [comment]
@loretoparisi I pushed the latest version to npm :)
