### ISSUE TITLE
nodehun with electron jenkins build error

### ISSUE THREAD

**Issue by TaeYeopKim** [Wulf/nodehun#93]
I am using electron, react frontend and nodejs backend.

I am trying to use nodehun in the project. Locally everything works fine, but when I build it on Jenkins and try to run it on another computer, its spitting out issues.

-----------------------------------------------------------------------------------------------------------------

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /data/jenkins/workspace/projectName/partOfDir/src/node_modules/nodehun/build/partOfDir/Nodehun.node: Error: /data/jenkins/workspace/projectName/partOfDir/src/node_modules/nodehun/build/partOfDir/Nodehun.node: cannot open shared object file: No such file or directory
    at Object.<anonymous> (/tmp/tmpDir/partOfDir/app/main.js:9:327237)
    at Object.<anonymous> (/tmp/tmpDir/partOfDir/app/main.js:9:327378)
    at n (/tmp/tmpDir/partOfDir/app/main.js:1:124)
    at Module.<anonymous> (/tmp/tmpDir/partOfDir/app/main.js:22:391650)
    at n (/tmp/tmpDir/partOfDir/app/main.js:1:124)
    at Object.<anonymous> (/tmp/tmpDir/partOfDir/app/main.js:9:327425)
    at n (/tmp/tmpDir/partOfDir/app/main.js:1:124)
    at /tmp/tmpDir/partOfDir/app/main.js:1:923
    at Object.<anonymous> (/tmp/tmpDir/partOfDir/app/main.js:1:934)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
`
-----------------------------------------------------------------------------------------------------------------

From the error message here is what I'm assuming: When jenkins is building, it builds nodehun and stores it in the /data/jenkins/... directory, and that is where my program will be reaching for in order to retrieve Nodehun.node. 
So when a local user tries to grab the built version and tries to use it it's complaining that /data/jenkins/... directory is not reachable which makes sense. 

is there a way to make it work, perhaps something like assigning a custom directory myself??

**Comment by Wulf** [comment]
@TaeYeopKim hey Tae, I'm not too familiar with Jenkins, could you give me more details?

**Comment by Wulf** [comment]
Closing this, feel free to reopen!
